### ISSUE TITLE
Not an issue but actually I like your approach to adding Sponsorblock segments and would like to get in touch


### ISSUE THREAD

**Issue by Villageslayer** [qaiik/sponsorBlockAuto#1]
V1llageslayer#7035

**Comment by ajayyy** [comment]
@Villageslayer Please read https://wiki.sponsor.ajay.app/w/Automating_Submissions

You can asks us questions on [Discord](https://discord.gg/sponsorblock)

**Comment by qaiik** [comment]
I got banned from your app and service permanently for some reason I forgot

**Comment by ajayyy** [comment]
Bans only happen for very good reason

**Comment by qaiik** [comment]
I really forgot it was probably because I was underage at the time or something

**Comment by ajayyy** [comment]
Are you still automating segments? We purged many badly written bots.

**Comment by qaiik** [comment]
No definitely not, this was an idea I had for like 5 hours
